name: DevOps Learning CI

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: CI Failure Practice
        run: |
          echo "Starting failure test..."
          exit 1

